server:
  port: 9292
  servlet:
    context-path: /springboot_lucene
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 123456
  mvc:  #视图解析
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

